let motive = document.querySelector(".motive")
let button = document.querySelector(".button")
let body = document.querySelector(".body")
let navigation_items = document.querySelector(".navigation__items")
let navigation_link0 = document.querySelector(".navigation__link0")
let navigation_link1 = document.querySelector(".navigation__link1")
let navigation_link2 = document.querySelector(".navigation__link2")
let navigation_link3 = document.querySelector(".navigation__link3")
let navigation_link4 = document.querySelector(".navigation__link4")
let navigation_link5 = document.querySelector(".navigation__link5")
let navigation_link6 = document.querySelector(".navigation__link6")

button.addEventListener("click", () => {
    button.classList.toggle("darkButton")
    body.classList.toggle("darkMotive")
    navigation_items.classList.toggle("darkBorder")
    navigation_link0.classList.toggle("darkLink")
    navigation_link1.classList.toggle("darkLink")
    navigation_link2.classList.toggle("darkLink")
    navigation_link3.classList.toggle("darkLink")
    navigation_link4.classList.toggle("darkLink")
    navigation_link5.classList.toggle("darkLink")
    navigation_link6.classList.toggle("darkLink")

    motive.innerText = body.classList.contains("darkMotive") ? "jasny" : "ciemny";
})
